from .base_tool import BaseTool

class AutoGeneratedAnalysisTool(BaseTool):
    """
    A tool that automatically generates its interface from the corresponding C# analysis tool
    using reflection to read the tool's arguments and description.
    """
    
    def __init__(self, tool_name, runcommand, tool_data):
        super().__init__()
        self.name = tool_name
        self.runcommand = runcommand
        self._tool_data = tool_data
        self._info = self._convert_tool_data_to_info(tool_data)
        
    @property
    def info(self):
        """Get complete tool information from JSON data"""
        return self._info
    
    def _convert_tool_data_to_info(self, tool_data):
        """Convert JSON tool data to the expected info format"""
        args = tool_data.get('arguments', [])
        
        return {
            'name': tool_data.get('name', self.name),
            'description': tool_data.get('description', f'Analysis tool: {self.name}'),
            'arguments': args
        }
        
    @property
    def description(self):
        """Get the tool description from the C# analysis tool"""
        return self.info.get('description', f'Analysis tool: {self.name}')
    
    @property
    def arguments(self):
        """Get argument information"""
        info = self.info
        return info.get('arguments', [])
    
    def get_usage_info(self):
        """Get comprehensive usage information for this tool"""
        data = self._tool_data
        usage_info = f"""Tool: {data['name']}
Description: {data['description']}

Usage: /{data['name']} <arguments>

Arguments:"""
        
        for arg in data.get('arguments', []):
            usage_info += f"\n  - {arg}"
            
        return usage_info
    
    
    def execute(self, args):
        """Execute the analysis tool with the provided arguments"""
        arg_list = args.split() if isinstance(args, str) and args else []
        
        return self.runcommand('dotnet', [
            'run', '--project', 'refactoring-tools/RoslynAnalysis/RoslynAnalysis.csproj',
            '--', self.name
        ] + arg_list)