from .base_tool import BaseTool

class BaseAutoGeneratedTool(BaseTool):
    """
    Base class for auto-generated tools that automatically generate their interface 
    from corresponding C# tools using reflection to read arguments and description.
    """
    
    def __init__(self, tool_name, runcommand, tool_data, tool_type):
        super().__init__()
        self.name = tool_name
        self.runcommand = runcommand
        self._tool_data = tool_data
        self._tool_type = tool_type
        self._info = self._convert_tool_data_to_info(tool_data)
        
    @property
    def info(self):
        """Get complete tool information from JSON data"""
        return self._info
    
    def _convert_tool_data_to_info(self, tool_data):
        """Convert JSON tool data to the expected info format"""
        args = tool_data.get('arguments', [])
        
        return {
            'name': tool_data.get('name', self.name),
            'description': tool_data.get('description', f'{self._tool_type} tool: {self.name}'),
            'arguments': args
        }
        
    @property
    def description(self):
        """Get the tool description from the C# tool"""
        return self.info.get('description', f'{self._tool_type} tool: {self.name}')
    
    @property
    def arguments(self):
        """Get argument information"""
        info = self.info
        return info.get('arguments', [])
    
    def get_usage_info(self):
        """Get comprehensive usage information for this tool"""
        data = self._tool_data
        usage_info = f"""Tool: {data['name']}
Description: {data['description']}

Usage: /{data['name']} <arguments>

Arguments:"""
        
        for arg in data.get('arguments', []):
            usage_info += f"\n  - {arg}"
            
        return usage_info
    
    def execute(self, args):
        """Execute the tool with the provided arguments"""
        arg_list = args.split() if isinstance(args, str) and args else []
        
        return self.runcommand('dotnet', [
            'run', '--project', self._get_project_path(),
            '--', self.name
        ] + arg_list)
    
    def _get_project_path(self):
        """Get the project path for the specific tool type - to be overridden by subclasses"""
        raise NotImplementedError("Subclasses must implement _get_project_path()")