from .base_auto_generated_tool import BaseAutoGeneratedTool

class AutoGeneratedAnalysisTool(BaseAutoGeneratedTool):
    """
    A tool that automatically generates its interface from the corresponding C# analysis tool
    using reflection to read the tool's arguments and description.
    """
    
    def __init__(self, tool_name, runcommand, tool_data):
        super().__init__(tool_name, runcommand, tool_data, "Analysis")
        
    def _get_project_path(self):
        """Get the project path for analysis tools"""
        return 'refactoring-tools/RoslynAnalysis/RoslynAnalysis.csproj'