from .base_auto_generated_tool import BaseAutoGeneratedTool

class AutoGeneratedTool(BaseAutoGeneratedTool):
    """
    A tool that automatically generates its interface from the corresponding C# refactoring tool
    using reflection to read the tool's arguments and description.
    """
    
    def __init__(self, tool_name, runcommand, tool_data):
        super().__init__(tool_name, runcommand, tool_data, "Refactoring")
        
    def _get_project_path(self):
        """Get the project path for refactoring tools"""
        return 'refactoring-tools/RoslynRefactoring/RoslynRefactoring.csproj'